name: engapp
description: Myanmar-focused English learning app (MVP scaffold)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0

  # Optional UI helpers
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/daily/
    - assets/strings/
